name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Go for use with actions
      uses: actions/setup-go@v1.0.0
      with:
        # The Go version to download (if necessary) and use. Example: 1.9.3
        version: # optional, default is 1.13
    - name: Build
      run: |
        export GOOS=windows
        mkdir -p /home/runner/go/src/github.com/gig-tech/windows-init
        cp -r * /home/runner/go/src/github.com/gig-tech/windows-init
        cd /home/runner/go/src/github.com/gig-tech/windows-init/app
        go get
        cd ../cmd/giginit
        export GOARCH=amd64
        go build
        mv giginit.exe giginit-amd64.exe
        export GOARCH=386
        go build
        mv giginit.exe giginit-386.exe
    - uses: actions/upload-artifact@v1
      with:
        name: GIG Windows Initializer AMD64
        path: /home/runner/go/src/github.com/gig-tech/windows-init/cmd/giginit/giginit-amd64.exe
    - uses: actions/upload-artifact@v1
      with:
        name: GIG Windows Initializer 386
        path: /home/runner/go/src/github.com/gig-tech/windows-init/cmd/giginit/giginit-amd64.exe
